name: Linting

on:
  push:
    branches:
      - develop
      - main
      - 'release/rocm-rel*'
  pull_request:
    branches:
      - develop
      - main
      - 'release/rocm-rel*'

jobs:
  call-workflow-passing-data:
    name: Documentation
    uses: ROCm/rocm-docs-core/.github/workflows/linting.yml@develop

  cmake-formatting:
    name: CMake File Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip
          python3 -m pip install gersemi
      - name: Run gersemi
        run: |
          gersemi --check .
          if [ $? -ne 0 ]; then
            echo "CMake files are not formatted correctly. Please run gersemi ..."
            echo "For example: \`gersemi -i .\`"
            exit 1
          fi

  source-formatting:
    name: Source Code Formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format
      - name: Make scripts executable
        run: chmod +x Scripts/CodeFormat/check_format.sh Scripts/CopyrightDate/check_copyright.sh
      - name: Run code format check
        run: ./Scripts/CodeFormat/check_format.sh HEAD
      - name: Run copyright check
        run: |
          opts="-qc"
          if [ "$(git config --get --type bool --default false hooks.updateCopyright)" = "true" ]; then
              opts="-qca"
          fi
          ./Scripts/CopyrightDate/check_copyright.sh "$opts"
      - name: Fail if formatting issues found
        run: git diff --exit-code
